// Exemplo 1

// Algoritmo "aguardando2"
//     Var cont: inteiro
// Inicio
//     cont <- 0
//     Enquanto (cont < 100) faça
//         escreva ("Aguarde...");
//         cont <- cont + 1
//     fimenquanto
// Fimalgoritmo

// Exemplo 2

Algoritmo "somaValores"
    Var val, soma: inteiro
Inicio
    soma <- 0
    enquanto (soma < 100) faca
        leia(val)
        soma <- soma + val
        escreval("Soma: ", soma)
    fimenquanto
Fimalgoritmo
